consul-server:
  restart: always
  tty: true
  ports:
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8302:8302
    - 8302:8302/udp
    - 8400:8400
    - 8500:8500
    - 8600:8600
    - 8600:8600/udp
  command: -bootstrap-expect=${server_count} -encrypt="${encryption}" -dc="${datacenter}"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: consul-server-datavolume
    io.rancher.scheduler.affinity:${host_label_type}: service=consul
    io.rancher.container.pull_image: always
  image: pk4media/consul-server:0.6
  volumes_from:
    - consul-server-datavolume
  environment:
    SERVER_COUNT: ${server_count}
consul-server-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data
  entrypoint: /bin/true
  image: busybox
