nexus-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  image: sonatype/nexus:2.11.2
  volumes:
  - ${NEXUS_VOLUME}/sonatype-work
nexus-server:
  ports:
  - ${NEXUS_PORT}:8081/tcp
  labels:
    io.rancher.sidekicks: nexus-data
  image: sonatype/nexus:2.11.2
  volumes_from:
  - nexus-data
