nexus-data:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: name=node01
  entrypoint:
  - /bin/true
  image: sonatype/nexus:2.11.2
  volumes:
  - /sonatype-work
nexus-server:
  ports:
  - 9001:8081/tcp
  labels:
    io.rancher.sidekicks: nexus-data
    io.rancher.scheduler.affinity:host_label: name=node01
  image: sonatype/nexus:2.11.2
  volumes_from:
  - nexus-data
