vsplunk:
  net: none
  image: busybox
  labels:
      io.rancher.container.start_once: true
  volumes:
    - ${SPLUNK_DIR}
splunk:
  image: outcoldman/splunk:latest
  hostname: splunk
  volumes_from:
    - vsplunk
  ports:
    - ${SPLUNK_PORT}:8000




