vsplunk:
  net: none
  image: busybox
  labels:
      io.rancher.container.start_once: true
  volumes:
    - /opt/splunk/etc
    - /opt/splunk/var
splunk:
  restart: always
  image: outcoldman/splunk:latest
  hostname: splunk
  volumes_from:
    - vsplunk
  labels:
    io.rancher.sidekicks: vsplunk
    io.rancher.container.pull_image: always
  ports:
    - ${SPLUNK_PORT}:8000




