.catalog:
  name: "PostgreSQL for Nuxeo"
  version: "9.4"
  description: "PostgreSQL"
  uuid: postgres-0
  questions:
    - variable: "dbname"
      description: "Default database that is created when the image is first started."
      label: "Postgres Database Name"
      type: "string"
      required: false
      default: "nuxeo"
    - variable: "dbuser"
      type: "string"
      label: "Postgres user"
      description: |
        is used in conjunction with POSTGRES_PASSWORD to set a user and its password. 
        This will create the specified user with superuser power and a database with the same name. 
        If it is not specified, then the default user of postgres will be used.
      default: "nuxeo"
    - variable: "dbpassword"
      type: "string"
      label: "Postgres password"
      description: |
        sets the superuser password for PostgreSQL. The default superuser is defined by the <<Postgres user>> variable
      default: "nuxeo"