.catalog:
  name: "Wordpress"
  version: "v2.0"
  description: "Wordpress server"
  uuid: wordpress-1
  questions: 
    - variable: "PORT"
      label: "Port"
      description: "Which TCP port the load balancer should listen on"
      default: 8080
      required: true
      type: "int"
    - variable: "PASSWORD"
      label: "Password"
      description: "Root password for Wordpress database"
      required: true
      type: "password"
      default: "password"
    - variable: "VOLUME"
      label: "Storage"
      description: "Persistent storage volume.  Either a filesystem path, or a Convoy volume name"
      required: true
      type: "string"
      default: "wordpress"
    - variable: "POOL"
      label: "Storage pool"
      description: "Name of Convoy storage pool, or blank for filesystem"
      required: false
      type: "string"
db:
  scale: 1
balancer:
  load_balancer_config: {}
wordpress:
  scale: 1

