broker:
  tty: true
  image: rawmind/rancher-kafka:0.8.2-6
  volumes:
  - /opt/kafka/data
  environment:
  - JVMFLAGS=-Xmx${kafka_mem}m -Xms${kafka_mem}m
  - CONFD_INTERVAL=${kafka_interval}
  - ZK_SERVICE=${zk_link}
  external_links:
  - ${zk_link}:zk
