.catalog:
  name: "Wordpress"
  version: "v1.2"
  description: "Wordpress server"
  uuid: wordpress-0
  questions: 
    - variable: "PORT"
      label: "Port"
      description: "Which TCP port the load balancer should listen on"
      default: 8080
      required: true
      type: "int"
    - variable: "PASSWORD"
      label: "Password"
      description: "Root password for Wordpress database"
      required: true
      type: "password"
      default: "password"
db:
  scale: 1
balancer:
  load_balancer_config: {}
wordpress:
  scale: 1

