name: gocd-server
description: |
  (Experimental) Gocd server
version: 16.1.0-rancher1
category: "Continuous Integration"
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.56.0
license: 
