docker-clean:
  restart: always
  image: cloudnautique/vol-cleanup
  privileged: true
  volumes:
    - /var/lib/docker:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: ${HOST_LABEL}
  command: -i 5
