myalfreso:
  tty: true
  image: docker.io/mikelasla/alfresco-standalone
  ports:
  - 18080:8080
  links:
    database: postgres
  stdin_open: true
database:
  environment:
    POSTGRES_PASSWORD: alfresco
    POSTGRES_USER: alfresco
    POSTGRES_DB: alfresco
  tty: true
  image: postgres
  stdin_open: true
